INSERT INTO [dbo].[M_ORG_T3]
           ([ParentId]
           ,[Level]
           ,[Code]
           ,[Name]
           ,[Type]
           ,[HasUDNo]
           ,[Independent]
           ,[SetadId]
           ,[Active]
           ,[NationalId]
           ,[PostalCode])
select [ParentId]
           ,[Level]
           ,'201811'--[Code]
           ,N'کلینیک ویژه فاضل تونی فردوس'--[Name]
           ,[Type]
           ,[HasUDNo]
           ,[Independent]
           ,[SetadId]
           ,[Active]
           ,[NationalId]
           ,[PostalCode]
		   from dbo.M_ORG_T3 where Code like '201810'  